# Project name should contain only lowercase characters and underscores
name: 'my_project'
version: '1.0.0'
config-version: 2

# Profile used by dbt
profile: 'my_project'

# File path configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  my_project:
    +materialized: view
